#!/bin/bash

# Git Remote and Online Operations Tutorial
# This script demonstrates working with git remotes (GitHub, GitLab, etc.)

echo "=== Git Remote and Online Operations Tutorial ==="
echo ""

echo "1. Understanding Git Remotes"
echo ""
echo "   A 'remote' is a version of your project hosted online"
echo "   GitHub, GitLab, Bitbucket are common remote hosting services"
echo "   Remotes enable collaboration, backup, and CI/CD"
echo ""
echo "   Common remote names:"
echo "   - origin: Default name for primary remote"
echo "   - upstream: Original repository (for forks)"
echo "   - backup: Personal backup repository"
echo ""

echo "2. Basic Remote Commands"
echo ""
echo "   # View configured remotes"
echo "   git remote -v"
echo "   # Shows: origin  https://github.com/user/repo.git (fetch)"
echo "   #       origin  https://github.com/user/repo.git (push)"
echo ""
echo "   # Add remote repository"
echo "   git remote add origin https://github.com/username/repo.git"
echo ""
echo "   # Add remote with SSH (recommended for frequent use)"
echo "   git remote add origin git@github.com:username/repo.git"
echo ""
echo "   # Show remote URL"
echo "   git remote get-url origin"
echo ""
echo "   # Show remote details"
echo "   git remote show origin"
echo "   # Shows: remote branches, HEAD, local branches tracking"
echo ""
echo "   # Rename remote"
echo "   git remote rename origin new-origin"
echo ""
echo "   # Remove remote"
echo "   git remote remove origin"
echo ""

echo "3. SSH vs HTTPS for GitHub"
echo ""
echo "   HTTPS:"
echo "   git remote add origin https://github.com/username/repo.git"
echo "   - Easy to set up"
echo "   - Requires password/token for every push"
echo "   - Good for occasional users"
echo ""
echo "   SSH:"
echo "   git remote add origin git@github.com:username/repo.git"
echo "   - Requires SSH key setup"
echo "   - No password needed after setup"
echo "   - More secure and convenient"
echo "   - Recommended for frequent users"
echo ""
echo "   # Setup SSH key"
echo "   ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "   # Copy public key: cat ~/.ssh/id_ed25519.pub"
echo "   # Add to GitHub: Settings > SSH and GPG keys > New SSH key"
echo ""

echo "4. Pushing Changes to Remote"
echo ""
echo "   # First push (set upstream)"
echo "   git push -u origin main"
echo "   # -u: Sets upstream tracking for current branch"
echo "   # Future pushes just need: git push"
echo ""
echo "   # Push to specific branch"
echo "   git push origin feature-branch"
echo ""
echo "   # Push all branches"
echo "   git push --all origin"
echo ""
echo "   # Push with tags"
echo "   git push origin --tags"
echo ""
echo "   # Force push (dangerous!)"
echo "   git push --force origin feature-branch"
echo ""
echo "   # Force push with lease (safer)"
echo "   git push --force-with-lease origin feature-branch"
echo "   # Checks if remote changed before forcing"
echo ""

echo "5. Pulling Changes from Remote"
echo ""
echo "   # Basic pull (fetch + merge)"
echo "   git pull origin main"
echo ""
echo "   # Pull with rebase (linear history)"
echo "   git pull --rebase origin main"
echo ""
echo "   # Pull without merging"
echo "   git fetch origin"
echo "   # Updates remote tracking branches, doesn't merge"
echo ""
echo "   # Fetch all remotes"
echo "   git fetch --all"
echo ""
echo "   # Fetch and prune (delete deleted remote branches)"
echo "   git fetch --prune origin"
echo ""
echo "   # Pull specific branch"
echo "   git pull origin feature-branch"
echo ""

echo "6. Cloning Repositories"
echo ""
echo "   # Clone repository"
echo "   git clone https://github.com/username/repo.git"
echo "   # Creates 'repo' directory and initializes"
echo ""
echo "   # Clone to specific directory"
echo "   git clone https://github.com/username/repo.git my-directory"
echo ""
echo "   # Clone specific branch"
echo "   git clone -b develop https://github.com/username/repo.git"
echo ""
echo "   # Clone with SSH"
echo "   git clone git@github.com:username/repo.git"
echo ""
echo "   # Shallow clone (no history, latest only)"
echo "   git clone --depth 1 https://github.com/username/repo.git"
echo "   # Faster for large repos"
echo ""
echo "   # Clone specific branch with depth"
echo "   git clone --depth 1 --branch develop https://github.com/username/repo.git"
echo ""

echo "7. Remote Branch Operations"
echo ""
echo "   # List remote branches"
echo "   git branch -r"
echo "   # Shows: origin/main, origin/develop, etc."
echo ""
echo "   # List all branches (local + remote)"
echo "   git branch -a"
echo ""
echo "   # Track remote branch locally"
echo "   git checkout --track origin/feature-branch"
echo "   # Shortcut:"
echo "   git checkout feature-branch"
echo "   # Creates local branch tracking remote"
echo ""
echo "   # Delete remote branch"
echo "   git push origin --delete feature-branch"
echo "   # Or:"
echo "   git push origin :feature-branch"
echo ""

echo "8. Working with Forks (upstream remote)"
echo ""
echo "   # Scenario: You forked someone's repository"
echo "   1. Clone your fork"
echo "      git clone git@github.com:your-username/repo.git"
echo "      cd repo"
echo ""
echo "   2. Add original repository as upstream"
echo "      git remote add upstream git@github.com:original-owner/repo.git"
echo ""
echo "   3. Fetch from upstream"
echo "      git fetch upstream"
echo ""
echo "   4. Merge upstream changes to your fork"
echo "      git checkout main"
echo "      git merge upstream/main"
echo "      git push origin main"
echo ""
echo "   5. View remotes"
echo "      git remote -v"
echo "      # origin  git@github.com:your-username/repo.git (fetch)"
echo "      # origin  git@github.com:your-username/repo.git (push)"
echo "      # upstream git@github.com:original-owner/repo.git (fetch)"
echo "      # upstream git@github.com:original-owner/repo.git (push)"
echo ""

echo "9. GitHub CLI (gh) for Remote Operations"
echo ""
echo "   # Install GitHub CLI"
echo "   brew install gh  # macOS"
echo "   # Or download from https://cli.github.com/"
echo ""
echo "   # Authenticate"
echo "   gh auth login"
echo ""
echo "   # Create repository from command line"
echo "   gh repo create my-new-repo --public --source=. --remote=origin"
echo ""
echo "   # View repository on GitHub"
echo "   gh repo view"
echo ""
echo "   # List pull requests"
echo "   gh pr list"
echo ""
echo "   # Create pull request"
echo "   gh pr create --title 'My PR' --body 'Description'"
echo ""
echo "   # View pull request
echo "   gh pr view 123"
echo ""
echo "   # Merge pull request"
echo "   gh pr merge 123"
echo ""

echo "10. Common Remote Workflows"
echo ""
echo "   Workflow A: Update feature branch with latest main"
echo "   ----------------------------------------------------"
echo "   git checkout feature/my-feature"
echo "   git fetch origin"
echo "   git rebase origin/main"
echo "   # Resolve conflicts if any"
echo "   git push --force-with-lease origin feature/my-feature"
echo ""

echo "   Workflow B: Collaborate on PR"
echo "   -----------------------------"
echo "   # Partner pushed new commit to shared branch"
echo "   git fetch origin"
echo "   git checkout feature/shared-feature"
echo "   git pull --rebase origin feature/shared-feature"
echo "   # Now you have their changes"
echo ""

echo "   Workflow C: Multiple remotes"
echo "   ---------------------------"
echo "   # Add backup remote"
echo "   git remote add backup git@github.com:your-username/repo-backup.git"
echo "   # Push to backup"
echo "   git push backup main"
echo "   # Pull from backup"
echo "   git pull backup main"
echo ""

echo "11. Remote Troubleshooting"
echo ""
echo "   # Check remote connectivity"
echo "   git ls-remote origin"
echo "   # Lists references on remote"
echo ""
echo "   # Check remote configuration"
echo "   git config --get remote.origin.url"
echo ""
echo "   # Test SSH connection"
echo "   ssh -T git@github.com"
echo ""
echo "   # View fetch/push URLs"
echo "   git remote -v"
echo ""
echo "   # Update remote URL"
echo "   git remote set-url origin git@github.com:username/new-repo.git"
echo ""

echo "12. Best Practices for Remote Operations"
echo ""
echo "   - Always fetch before pulling"
echo "   - Use pull --rebase for cleaner history"
echo "   - Never force push to shared branches"
echo "   - Use force-with-lease instead of force"
echo "   - Pull frequently to minimize conflicts"
echo "   - Set upstream tracking with -u flag"
echo "   - Use SSH keys for frequent pushing"
echo "   - Regularly fetch --prune to clean up"
echo "   - Protect main branch from direct pushes"
echo "   - Use pull requests for all changes"
echo ""

echo "13. Quick Reference Card"
echo ""
echo "   git remote -v                    # List remotes"
echo "   git remote add origin URL         # Add remote"
echo "   git remote remove origin         # Remove remote"
echo "   git clone URL                    # Clone repository"
echo "   git fetch origin                 # Fetch from remote"
echo "   git pull origin main             # Pull and merge"
echo "   git pull --rebase origin main    # Pull with rebase"
echo "   git push -u origin main          # Push with upstream"
echo "   git push --force-with-lease      # Safe force push"
echo "   git push origin --delete branch  # Delete remote branch"
echo "   git branch -r                    # List remote branches"
echo "   git branch -a                    # List all branches"
echo ""

echo "=== End of Git Remote and Online Operations Tutorial ==="
