#!/bin/bash

# Git Stash Tutorial
# This script demonstrates git stash for managing work in progress

echo "=== Git Stash Tutorial ==="
echo ""

echo "1. What is Git Stash?"
echo ""
echo "   Stash temporarily saves your uncommitted changes"
echo "   Lets you switch branches without committing"
echo "   Perfect for work in progress (WIP)"
echo "   Stacks multiple stashes like a stack"
echo ""

echo "2. Basic Stash Commands"
echo ""
echo "   # Stash current changes"
echo "   git stash"
echo "   # This: stages all changes, resets working directory"
echo ""
echo "   # Stash with message"
echo "   git stash save 'Work on user authentication'"
echo ""
echo "   # View all stashes"
echo "   git stash list"
echo "   # Output: stash@{0}: On main: Work on user auth"
echo ""
echo "   # Apply most recent stash"
echo "   git stash apply"
echo "   # Keeps stash in list"
echo ""
echo "   # Apply specific stash"
echo "   git stash apply stash@{1}"
echo ""
echo "   # Pop most recent stash (apply + remove)"
echo "   git stash pop"
echo ""
echo "   # Drop specific stash"
echo "   git stash drop stash@{0}"
echo ""
echo "   # Clear all stashes"
echo "   git stash clear"
echo ""

echo "3. Stash Workflow Examples"
echo ""
echo "   Scenario A: Emergency bug fix needed"
echo "   -----------------------------------"
echo "   1. Working on feature, not ready to commit"
echo "      git status  # Shows modified files"
echo ""
echo "   2. Stash current work"
echo "      git stash save 'WIP: User auth feature'"
echo ""
echo "   3. Switch to main, fix bug"
echo "      git checkout main"
echo "      git checkout -b hotfix/critical-bug"
echo "      # Fix and commit bug"
echo "      git add ."
echo "      git commit -m 'Fix critical bug'"
echo "      git push origin hotfix/critical-bug"
echo ""
echo "   4. Return to feature work"
echo "      git checkout feature/user-auth"
echo "      git stash pop"
echo "      # Continue where you left off"
echo ""

echo "   Scenario B: Update feature branch with latest main"
echo "   ----------------------------------------------------"
echo "   1. On feature branch with uncommitted work"
echo "      git checkout feature/new-feature"
echo "      # Have uncommitted changes"
echo ""
echo "   2. Stash work"
echo "      git stash"
echo ""
echo "   3. Pull latest from main"
echo "      git fetch origin"
echo "      git rebase origin/main"
echo ""
echo "   4. Apply stashed work"
echo "      git stash pop"
echo "      # Resolve any conflicts if needed"
echo ""

echo "   Scenario C: Test different approaches"
echo "   --------------------------------------"
echo "   1. First approach"
echo "      # Write code for approach A"
echo "      git stash save 'Approach A'"
echo ""
echo "   2. Second approach"
echo "      # Write code for approach B"
echo "      git stash save 'Approach B'"
echo ""
echo "   3. Third approach"
echo "      # Write code for approach C"
echo "      git stash save 'Approach C'"
echo ""
echo "   4. Compare approaches"
echo "      git stash list"
echo "      git stash show stash@{2}  # View approach A"
echo "      git stash show stash@{1}  # View approach B"
echo "      git stash apply stash@{0}  # Apply approach C"
echo ""

echo "4. Advanced Stash Options"
echo ""
echo "   a) Stash untracked files"
echo "      git stash -u"
echo "      # Or explicitly:"
echo "      git stash --include-untracked"
echo ""
echo "   b) Stash all files (including ignored)"
echo "      git stash -a"
echo "      # Or explicitly:"
echo "      git stash --all"
echo ""
echo "   c) Stash only specific files"
echo "      git stash push -m 'Stash specific files' file1.txt file2.txt"
echo ""
echo "   d) Stash with keep-index (keep staged files)"
echo "      git stash --keep-index"
echo "      # Stashes unstaged changes, keeps staged changes"
echo ""
echo "   e) Create branch from stash"
echo "      git stash branch test-branch stash@{1}"
echo "      # Creates new branch from stash state"
echo "   # Applies stash, deletes it"
echo ""

echo "5. Viewing Stash Contents"
echo ""
echo "   # Show files changed in stash"
echo "   git stash show"
echo "   # Summary of most recent stash"
echo ""
echo "   # Show specific stash files"
echo "   git stash show stash@{2}"
echo ""
echo "   # Show diff of stash"
echo "   git stash show -p"
echo "   # Full diff of most recent stash"
echo ""
echo "   # Show diff of specific stash"
echo "   git stash show -p stash@{1}"
echo ""
echo "   # View stash without applying"
echo "   git diff stash@{0}"
echo "   git diff HEAD..stash@{0}"
echo ""

echo "6. Stash Conflict Resolution"
echo ""
echo "   # If stash apply causes conflicts:"
echo "   a) Git shows conflicted files"
echo "   b) Resolve conflicts in editor"
echo "   c) Stage resolved files"
echo "      git add resolved-file.txt"
echo "   d) Drop the stash (manually)"
echo "      git stash drop stash@{0}"
echo ""
echo "   # Note: Stash doesn't track conflicts like merge"
echo "   # You must manually drop after resolving"
echo ""

echo "7. Stash vs Commit"
echo ""
echo "   STASH:"
echo "   - Temporary storage"
echo "   - Not part of history"
echo "   - Work in progress"
echo "   - No commit message required"
echo "   - Good for: quick context switches, experiments"
echo ""
echo "   COMMIT:"
echo "   - Permanent record"
echo "   - Part of git history"
echo "   - Complete unit of work"
echo "   - Requires commit message"
echo "   - Good for: completed work, code review"
echo ""
echo "   RULE OF THUMB:"
echo "   - Use stash if you'll resume work within hours"
echo "   - Use commit if work is complete or days long"
echo ""

echo "8. Stash Stack Operations"
echo ""
echo "   # Stash is a LIFO stack (Last In First Out)"
echo ""
echo "   # Push new stash to stack"
echo "   git stash push -m 'New work'"
echo "   # Becomes stash@{0}"
echo ""
echo "   # View stack"
echo "   git stash list"
echo "   # stash@{0}: Newest"
echo "   # stash@{1}: Previous"
echo "   # stash@{2}: Even older"
echo ""
echo "   # Pop from stack (removes top)"
echo "   git stash pop"
echo "   # Removes and applies stash@{0}"
echo ""
echo "   # Apply without removing"
echo "   git stash apply stash@{0}"
echo "   # Stash remains in list"
echo ""

echo "9. Common Stash Patterns"
echo ""
echo "   a) Context Switching"
echo "      # Working on feature A"
echo "      git stash save 'Feature A partial'"
echo ""
echo "      # Switch to feature B"
echo "      git checkout feature-B"
echo "      # Work on B, commit, push"
echo ""
echo "      # Back to feature A"
echo "      git checkout feature-A"
echo "      git stash pop"
echo ""
echo "   b) Drafting Multiple Ideas"
echo "      git stash save 'Idea 1: User auth'"
echo "      git stash save 'Idea 2: OAuth integration'"
echo "      git stash save 'Idea 3: Token-based auth'"
echo ""
echo "      # Test each idea"
echo "      git stash apply stash@{2}"
echo "      # Test, then:"
echo "      git stash drop stash@{2}"
echo ""
echo "   c) Safe Updates"
echo "      # Have uncommitted work"
echo "      git stash"
echo ""
echo "      # Update repository"
echo "      git pull --rebase"
echo ""
echo "      # Apply work on top"
echo "      git stash pop"
echo "      # Resolve conflicts if any"
echo ""

echo "10. Stash Best Practices"
echo ""
echo "   - Always add descriptive stash messages"
echo "   - Don't keep stashes for weeks (commit instead)"
echo "   - Clean up old stashes regularly"
echo "   - Use stash list to review before clearing"
echo "   - Remember stash is local (not pushed to remote)"
echo "   - Stash before git pull to avoid conflicts"
echo "   - Use stash -u to include new files"
echo "   - Consider commits for long-running work"
echo ""

echo "11. Stash Quick Reference"
echo ""
echo "   git stash              # Stash current work"
echo "   git stash save 'msg'  # Stash with message"
echo "   git stash list         # List all stashes"
echo "   git stash show         # Show stash summary"
echo "   git stash show -p      # Show stash diff"
echo "   git stash apply        # Apply most recent"
echo "   git stash pop          # Apply and remove"
echo "   git stash drop         # Remove stash"
echo "   git stash clear        # Remove all stashes"
echo "   git stash branch name  # Create branch from stash"
echo "   git stash -u           # Include untracked files"
echo ""

echo "=== End of Git Stash Tutorial ==="
