#!/bin/bash

# Git Merge Tutorial
# This script demonstrates different merge strategies

echo "=== Git Merge Tutorial ==="
echo ""

echo "1. Basic merge (fast-forward)"
echo ""
echo "   # Scenario: main branch ahead of feature branch"
echo "   git checkout main"
echo "   git log --oneline --graph"
echo "   git merge feature-branch"
echo "   git log --oneline --graph"
echo "   # If fast-forward: main just moves to feature-branch"
echo ""

echo "2. Merge commit (non-fast-forward)"
echo ""
echo "   # Scenario: both branches have diverged"
echo "   git checkout main"
echo "   git merge feature-branch"
echo "   # Creates merge commit with both parents"
echo "   git log --oneline --graph --all"
echo ""

echo "3. Merge with no-ff (no fast-forward)"
echo ""
echo "   # Always create merge commit"
echo "   git merge --no-ff feature-branch"
echo "   # Benefits: Preserves branch history"
echo "   git log --oneline --graph --all"
echo ""

echo "4. Abort merge"
echo ""
echo "   # If merge conflicts or you want to cancel"
echo "   git merge --abort"
echo "   # This returns to state before merge"
echo ""

echo "5. Resolve merge conflicts"
echo ""
echo "   a) Identify conflicted files"
echo "      git status"
echo ""
echo "   b) Open conflicted files in editor"
echo "      # Files will have conflict markers:"
echo "      # <<<<<<< HEAD"
echo "      # Changes from current branch"
echo "      # ======="
echo "      # Changes from incoming branch"
echo "      # >>>>>>> feature-branch"
echo ""
echo "   c) Edit file to resolve conflicts"
echo "      # Remove markers and choose correct content"
echo ""
echo "   d) Stage resolved files"
echo "      git add resolved-file.txt"
echo ""
echo "   e) Complete merge"
echo "      git commit -m 'Resolve merge conflicts'"
echo "   # Note: Git will auto-generate commit message"
echo ""

echo "6. Merge strategies"
echo ""
echo "   a) Default merge (recursive)"
echo "      git merge feature-branch"
echo "      # Uses 3-way merge algorithm"
echo ""
echo "   b) Octopus merge (merge multiple branches)"
echo "      git merge branch1 branch2 branch3"
echo "      # Merges multiple branches into one"
echo ""
echo "   c) Ours strategy (always prefer current branch)"
echo "      git merge -s ours feature-branch"
echo "      # Discards changes from feature-branch"
echo ""
echo "   d) Theirs strategy (prefer incoming branch)"
echo "      # Note: No explicit '-s theirs' in older git"
echo "      # Workaround:"
echo "      git merge -s recursive -X theirs feature-branch"
echo ""

echo "7. Useful merge options"
echo ""
echo "   a) Squash merge (combine all commits into one)"
echo "      git merge --squash feature-branch"
echo "      git commit -m 'Squashed feature-branch'"
echo "      # Benefits: Cleaner history"
echo ""
echo "   b) Edit merge commit message"
echo "      git merge --edit feature-branch"
echo ""
echo "   c) Don't commit merge automatically"
echo "      git merge --no-commit feature-branch"
echo "      # Useful for reviewing before committing"
echo ""
echo "   d) Verbose merge output"
echo "      git merge --verbose feature-branch"
echo ""

echo "8. Advanced merge conflict resolution"
echo ""
echo "   a) Use specific merge strategy option"
echo "      git merge -X ours feature-branch"
echo "      # Prefer current changes for all conflicts"
echo ""
echo "   b) Use diff tool for conflicts"
echo "      git mergetool"
echo "      # Opens configured diff tool (vimdiff, opendiff, etc.)"
echo ""
echo "   c) Check which tool is configured"
echo "      git config --get merge.tool"
echo ""
echo "   d) Configure merge tool"
echo "      git config --global merge.tool opendiff"
echo "      # Options: vimdiff, opendiff, p4merge, etc."
echo ""

echo "9. Post-merge cleanup"
echo ""
echo "   # Delete merged branch"
echo "   git branch -d feature-branch"
echo "   # Force delete if not merged"
echo "   git branch -D feature-branch"
echo ""
echo "   # Push updated main branch"
echo "   git push origin main"
echo ""
echo "   # Delete remote branch"
echo "   git push origin --delete feature-branch"
echo ""

echo "10. Visualize merge history"
echo ""
echo "    # Simple graph"
echo "    git log --oneline --graph"
echo ""
echo "    # All branches"
echo "    git log --oneline --graph --all"
echo ""
echo "    # Decorated with branch names"
echo "    git log --oneline --graph --decorate --all"
echo ""
echo "    # Interactive visualization"
echo "    gitk --all"
echo "    # or"
echo "    git log --graph --all --color"
echo ""

echo "=== End of Git Merge Tutorial ==="
