#!/bin/bash

# Git Rebase Tutorial
# This script demonstrates git rebase operations

echo "=== Git Rebase Tutorial ==="
echo ""

echo "1. What is Rebase?"
echo ""
echo "   Rebase moves your branch to the tip of another branch"
echo "   Creates new commits (replays your work on top)"
echo "   Results in linear, cleaner history"
echo ""

echo "2. Basic rebase"
echo ""
echo "   # Scenario: Your feature branch is behind main"
echo "   git checkout feature-branch"
echo "   git log --oneline"
echo ""
echo "   # Rebase onto main"
echo "   git rebase main"
echo "   # This moves feature-branch to tip of main"
echo "   git log --oneline --graph"
echo ""

echo "3. Interactive rebase (modify commits)"
echo ""
echo "   # Rebase last 5 commits"
echo "   git rebase -i HEAD~5"
echo ""
echo "   # Or rebase from a specific commit"
echo "   git rebase -i <commit-hash>"
echo ""
echo "   # Interactive commands:"
echo "   pick  = Use commit as-is"
echo "   reword = Edit commit message"
echo "   edit = Pause before committing"
echo "   squash = Combine with previous commit"
echo "   fixup = Like squash, discard message"
echo "   exec  = Run shell command"
echo "   drop  = Remove commit"
echo ""

echo "4. Rebase examples"
echo ""
echo "   a) Fix typo in last commit"
echo "      git add fixed-file.txt"
echo "      git commit --amend -m 'Fixed typo'"
echo "      # Or use interactive rebase"
echo ""

echo "   b) Combine last 3 commits"
echo "      git rebase -i HEAD~3"
echo "      # Change 2nd and 3rd to 'squash'"
echo "      # Save and edit combined message"
echo ""

echo "   c) Reorder commits"
echo "      git rebase -i HEAD~3"
echo "      # Reorder lines to change commit order"
echo "      # Save and continue"
echo ""

echo "   d) Split a commit into two"
echo "      git rebase -i HEAD~1"
echo "      # Change 'pick' to 'edit'"
echo "      # Reset last commit"
echo "      git reset HEAD^"
echo "      # Create new commits"
echo "      git add part1.txt"
echo "      git commit -m 'Part 1'"
echo "      git add part2.txt"
echo "      git commit -m 'Part 2'"
echo "      # Continue rebase"
echo "      git rebase --continue"
echo ""

echo "5. Rebase conflicts"
echo ""
echo "   # When rebase encounters conflicts:"
echo "   a) Git pauses and shows conflict files"
echo "   b) Resolve conflicts in editor"
echo "   c) Stage resolved files"
echo "      git add resolved-file.txt"
echo "   d) Continue rebase"
echo "      git rebase --continue"
echo "   e) Or skip current commit (rare)"
echo "      git rebase --skip"
echo "   f) Or abort entire rebase"
echo "      git rebase --abort"
echo ""

echo "6. Rebase vs Merge"
echo ""
echo "   MERGE:"
echo "   - Preserves true history"
echo "   - Creates merge commit"
echo "   - Shows parallel development"
echo "   - Better for public/shared history"
echo "   - Example: git merge main"
echo ""
echo "   REBASE:"
echo "   - Creates linear history"
echo "   - Replays commits on new base"
echo "   - Cleaner, easier to read"
echo "   - Better for local/private branches"
echo "   - Example: git rebase main"
echo ""

echo "7. Advanced rebase scenarios"
echo ""
echo "   a) Rebase onto different branch"
echo "      git rebase --onto target-branch source-branch branch-to-move"
echo "      # Moves branch-to-move after target-branch"
echo "      # Instead of after source-branch"
echo ""
echo "   b) Rebase multiple branches"
echo "      git checkout feature1"
echo "      git rebase main"
echo "      git checkout feature2"
echo "      git rebase feature1"
echo ""

echo "   c) Cherry-pick (rebase single commit)"
echo "      git cherry-pick <commit-hash>"
echo "      # Applies specific commit to current branch"
echo ""
echo "   d) Rebase with autostash"
echo "      git rebase -i --autostash main"
echo "      # Stashes changes before rebase, applies after"
echo ""

echo "8. Golden Rules for Rebase"
echo ""
echo "   1. Never rebase public/shared branches"
echo "      - Rewrites history"
echo "      - Breaks other developers' repos"
echo "      - Only rebase local branches"
echo ""
echo "   2. Rebase before pushing"
echo "      - Pull with rebase to stay up to date"
echo "      git pull --rebase"
echo "      - Or fetch and rebase"
echo "      git fetch origin"
echo "      git rebase origin/main"
echo ""
echo "   3. Force push after rebase"
echo "      git push --force-with-lease origin feature-branch"
echo "      # Safer than --force (checks if remote changed)"
echo ""
echo "   4. Resolve conflicts during rebase"
echo "      - Take time to resolve properly"
echo "      - Test after each resolution"
echo "      - Commit resolution and continue"
echo ""

echo "9. Rebase workflow example"
echo ""
echo "   # Typical feature development workflow"
echo ""
echo "   1. Create feature branch"
echo "      git checkout -b feature/new-feature"
echo ""
echo "   2. Work and commit"
echo "      git add ."
echo "      git commit -m 'Start feature'"
echo "      git add ."
echo "      git commit -m 'Add more'"
echo ""
echo "   3. Update with latest main"
echo "      git fetch origin"
echo "      git rebase origin/main"
echo "      # Resolve conflicts if any"
echo ""
echo "   4. Clean up commits (optional)"
echo "      git rebase -i HEAD~3"
echo "      # Squash/reorder as needed"
echo ""
echo "   5. Push with force"
echo "      git push --force-with-lease origin feature/new-feature"
echo ""

echo "10. Rebase utilities"
echo ""
echo "    # Check rebase status"
echo "    git status"
echo "    # Shows 'rebase in progress' if active"
echo ""
echo "    # View rebase todo list"
echo "    cat .git/rebase-merge/git-rebase-todo"
echo ""
echo "    # Continue paused rebase"
echo "    git rebase --continue"
echo ""
echo "    # Skip current commit"
echo "    git rebase --skip"
echo ""
echo "    # Abort entire rebase"
echo "    git rebase --abort"
echo ""

echo "=== End of Git Rebase Tutorial ==="
