#!/bin/bash

# Git Collaboration Tutorial
# This script demonstrates how to collaborate using git

echo "=== Git Collaboration Tutorial ==="
echo ""

echo "1. Create a new repository on GitHub/GitLab (Step by Step)"
echo ""
echo "   a) Go to https://github.com/new"
echo "   b) Repository name: my-project"
echo "   c) Description: My collaboration project"
echo "   d) Choose: Public or Private"
echo "   e) DO NOT initialize with README, .gitignore, or license"
echo "   f) Click 'Create repository'"
echo ""

echo "2. Clone the empty repository locally"
echo "   git clone https://github.com/username/my-project.git"
echo "   cd my-project"
echo ""

echo "3. Initialize your local project"
echo "   git init"
echo "   # Create initial files"
echo "   echo '# My Project' > README.md"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo ""

echo "4. Push to remote repository"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "5. Add collaborators to your repository"
echo ""
echo "   a) Go to your repository on GitHub"
echo "   b) Click 'Settings' tab"
echo "   c) Click 'Collaborators' on left sidebar"
echo "   d) Click 'Add people'"
echo "   e) Enter collaborator's username or email"
echo "   f) Choose access level: 'Write' (can push) or 'Admin'"
echo "   g) Click 'Add collaborator'"
echo "   h) Collaborator will receive email invitation"
echo ""

echo "6. Collaborator workflow"
echo ""
echo "   a) Collaborator clones the repository"
echo "      git clone https://github.com/username/my-project.git"
echo "      cd my-project"
echo ""
echo "   b) Collaborator creates a new branch"
echo "      git checkout -b feature/new-feature"
echo ""
echo "   c) Collaborator makes changes and commits"
echo "      # Edit files"
echo "      git add ."
echo "      git commit -m 'Add new feature'"
echo ""
echo "   d) Collaborator pushes their branch"
echo "      git push -u origin feature/new-feature"
echo ""
echo "   e) Collaborator creates Pull Request"
echo "      - Go to repository on GitHub"
echo "      - Click 'Pull requests' tab"
echo "      - Click 'New pull request'"
echo "      - Select branch: feature/new-feature"
echo "      - Click 'Create pull request'"
echo "      - Add description and submit"
echo ""

echo "7. Owner reviews and merges"
echo ""
echo "   a) Review Pull Request on GitHub"
echo "   b) Add comments or request changes if needed"
echo "   c) If satisfied, click 'Merge pull request'"
echo "   d) Choose merge type: Merge commit / Squash / Rebase"
echo "   e) Delete branch after merge"
echo ""

echo "8. Update local repository after merge"
echo "   git checkout main"
echo "   git pull origin main"
echo ""

echo "9. Resolve conflicts (if any)"
echo "   # After pulling, if conflicts exist:"
echo "   git status"
echo "   # Open conflicting files and resolve conflicts"
echo "   git add resolved-file.txt"
echo "   git commit -m 'Resolve merge conflicts'"
echo ""

echo "10. Common collaboration commands"
echo ""
echo "    # View remote repositories"
echo "    git remote -v"
echo ""
echo "    # Add remote repository"
echo "    git remote add origin https://github.com/username/my-project.git"
echo ""
echo "    # Remove remote repository"
echo "    git remote remove origin"
echo ""
echo "    # Fetch all branches from remote"
echo "    git fetch --all"
echo ""
echo "    # Pull and rebase in one command"
echo "    git pull --rebase"
echo ""
echo "    # View pull requests"
echo "    gh pr list"
echo ""
echo "    # Create pull request from command line"
echo "    gh pr create --title 'My PR' --body 'Description'"
echo ""

echo "=== End of Git Collaboration Tutorial ==="
