#!/bin/bash

# Git Branching Strategy Tutorial
# This script demonstrates common git branching strategies

echo "=== Git Branching Strategy Tutorial ==="
echo ""

echo "1. Basic Branching Commands"
echo ""
echo "   # List branches"
echo "   git branch"
echo "   git branch -a  # Include remote branches"
echo ""
echo "   # Create new branch"
echo "   git branch feature/new-feature"
echo ""
echo "   # Switch to branch"
echo "   git checkout feature/new-feature"
echo "   # Or use newer command"
echo "   git switch feature/new-feature"
echo ""
echo "   # Create and switch in one command"
echo "   git checkout -b feature/new-feature"
echo "   # Or"
echo "   git switch -c feature/new-feature"
echo ""
echo "   # Rename branch"
echo "   git branch -m old-name new-name"
echo ""
echo "   # Delete branch"
echo "   git branch -d feature/old-feature"
echo "   git branch -D feature/old-feature  # Force delete"
echo ""

echo "2. Main Branch Strategies"
echo ""
echo "   a) Git Flow (Complex, systematic)"
echo "      - master: Production code"
echo "      - develop: Development code"
echo "      - feature/*: New features"
echo "      - release/*: Prepare for release"
echo "      - hotfix/*: Emergency production fixes"
echo "      - support/*: Long-term maintenance"
echo ""
echo "   b) GitHub Flow (Simple, continuous)"
echo "      - main: Production-ready code"
echo "      - feature/*: Feature branches"
echo "      - Pull requests for all changes"
echo "      - Continuous deployment"
echo ""
echo "   c) GitLab Flow (GitHub Flow + environments)"
echo "      - main: Production code"
echo "      - feature/*: Feature branches"
echo "      - environment/*: Deploy to different stages"
echo "      - Merge through production environment"
echo ""
echo "   d) Trunk-Based Development (No long-lived branches)"
echo "      - main/trunk: All development"
echo "   - Feature flags instead of branches"
echo "      - Continuous integration/deployment"
echo "      - Very small, frequent commits"
echo ""

echo "3. Git Flow Workflow (Detailed)"
echo ""
echo "   a) Master branch (production)"
echo "      - Always deployable"
echo "      - Tags for releases"
echo "      - Direct commits disabled"
echo ""
echo "   b) Develop branch (integration)"
echo "      - Latest development"
echo "      - Features merged here"
echo "      - Pre-release testing"
echo ""
echo "   c) Feature branches (features/feature-name)"
echo "      git checkout -b feature/user-auth develop"
echo "      # Work and commit"
echo "      git checkout develop"
echo "      git merge --no-ff feature/user-auth"
echo "      git branch -d feature/user-auth"
echo ""
echo "   d) Release branches (release/v1.0.0)"
echo "      git checkout -b release/v1.0.0 develop"
echo "      # Final testing, bug fixes"
echo "      git checkout master"
echo "      git merge --no-ff release/v1.0.0"
echo "      git tag -a v1.0.0 -m 'Release v1.0.0'"
echo "      git checkout develop"
echo "      git merge --no-ff release/v1.0.0"
echo "      git branch -d release/v1.0.0"
echo ""
echo "   e) Hotfix branches (hotfix/v1.0.1)"
echo "      git checkout -b hotfix/v1.0.1 master"
echo "      # Fix critical bug"
echo "      git checkout master"
echo "      git merge --no-ff hotfix/v1.0.1"
echo "      git tag -a v1.0.1 -m 'Hotfix v1.0.1'"
echo "      git checkout develop"
echo "      git merge --no-ff hotfix/v1.0.1"
echo "      git branch -d hotfix/v1.0.1"
echo ""

echo "4. GitHub Flow Workflow (Recommended for most teams)"
echo ""
echo "   1. Create feature branch from main"
echo "      git checkout -b feature/new-feature main"
echo ""
echo "   2. Make changes and commit"
echo "      git add ."
echo "      git commit -m 'Add new feature'"
echo ""
echo "   3. Push to remote"
echo "      git push -u origin feature/new-feature"
echo ""
echo "   4. Create Pull Request"
echo "      # On GitHub UI"
echo "      # Add description, tests, review"
echo ""
echo "   5. Review and discuss"
echo "      # Team reviews code"
echo "      # Address feedback"
echo "      # Update PR with new commits"
echo ""
echo "   6. Merge to main"
echo "      # Squash or merge commits"
echo "      # Delete feature branch"
echo ""
echo "   7. Deploy main to production"
echo "      # Automated or manual"
echo ""

echo "5. Branch Naming Conventions"
echo ""
echo "   # Feature branches"
echo "   feature/user-authentication"
echo "   feature/add-payment-gateway"
echo "   feature/refactor-database"
echo ""
echo "   # Bugfix branches"
echo "   bugfix/login-error"
echo "   fix/memory-leak"
echo "   hotfix/critical-security-issue"
echo ""
echo "   # Release branches"
echo "   release/v1.0.0"
echo "   release/v2.5.0-rc1"
echo ""
echo "   # Experiment branches"
echo "   experiment/new-ui"
echo "   spike/investigate-redis"
echo "   prototype/api-redesign"
echo ""
echo "   # Personal branches"
echo "   wip/john/user-auth"
echo "   draft/user-profile-page"
echo ""

echo "6. Branch Protection Rules (GitHub/GitLab)"
echo ""
echo "   # Protect main/master branch:"
echo "   - Require pull request reviews"
echo "   - Require status checks to pass"
echo "   - Require branches to be up to date"
echo "   - Restrict who can push"
echo "   - Include administrators"
echo "   - Require linear history"
echo "   - Block force pushes"
echo ""
echo "   # Set via GitHub UI:"
echo "   Settings > Branches > Add rule"
echo ""

echo "7. Long-Lived vs Short-Lived Branches"
echo ""
echo "   # Short-lived (recommended)"
echo "   - Feature branches: 1-3 days"
echo "   - Bugfix branches: < 1 day"
echo "   - Release branches: 1-2 weeks"
echo "   - Benefits: Less merge conflicts, easier review"
echo ""
echo "   # Long-lived (use carefully)"
echo "   - Develop branch (Git Flow)"
echo "   - Integration branches"
echo "   - Experimental branches"
echo "   - Risks: More conflicts, stale code"
echo ""

echo "8. Branch Workflows Comparison"
echo ""
echo "   GIT FLOW:"
echo "   Pros:"
echo "   - Structured, systematic"
echo "   - Clear release process"
echo "   - Separate production and development"
echo ""
echo "   Cons:"
echo "   - Complex for small teams"
echo "   - Multiple long-lived branches"
echo "   - More merge operations"
echo "   Use for: Enterprise, releases every 1-3 months"
echo ""
echo "   GITHUB FLOW:"
echo "   Pros:"
echo "   - Simple, easy to understand"
echo "   - Continuous deployment"
echo "   - Single main branch"
echo ""
echo "   Cons:"
echo "   - Requires good automated testing"
echo "   - Requires feature flags"
echo "   Use for: SaaS, weekly releases, agile teams"
echo ""
echo "   TRUNK-BASED:"
echo "   Pros:"
echo "   - No merge conflicts"
echo "   - Faster feedback"
echo "   - Very simple"
echo ""
echo "   Cons:"
echo "   - Requires extensive automation"
echo "   - Feature flags mandatory"
echo "   - High discipline required"
echo "   Use for: Large teams, daily releases, mature CI/CD"
echo ""

echo "9. Choosing the Right Strategy"
echo ""
echo "   # Use GitHub Flow if:"
echo "   - Small to medium team (1-20 developers)"
echo "   - Continuous deployment"
echo "   - Good CI/CD pipeline"
echo "   - Web services/mobile apps"
echo ""
echo "   # Use Git Flow if:"
echo "   - Large enterprise team"
echo "   - Scheduled releases (1-3 months)"
echo "   - Multiple production versions"
echo "   - Complex release coordination"
echo ""
echo "   # Use Trunk-Based if:"
echo "   - Very large team (20+ developers)"
echo "   - Daily or hourly releases"
echo "   - Mature infrastructure"
echo "   - Strong engineering culture"
echo ""

echo "10. Best Practices for Any Strategy"
echo ""
echo "   - Always branch from main/master"
echo "   - Keep branches short-lived (< 1 week)"
echo "   - Use descriptive branch names"
echo "   - Write clear commit messages"
echo "   - Review all code via Pull Requests"
echo "   - Protect main branch from direct pushes"
echo "   - Require automated tests before merge"
echo "   - Delete merged feature branches"
echo "   - Keep main branch deployable at all times"
echo ""

echo "=== End of Git Branching Strategy Tutorial ==="
